version: "2"

services:

  ioc:
    build: ioc
    image: pyepics-workshop-ioc
    entrypoint: "true"

  ioc-launcher:
    build: ioc-launcher
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ioc-relay:
    build: ioc-relay
    ports:
      - 5678:5678
    environment:
      - EPICS_CA_ADDR_LIST=gateway

  ioc-dashboard:
    build: ioc-dashboard
    ports:
      - 9000:9000

  gateway:
    image: dmscid/epics-gateway
    command: -cip 172.111.255.255
    ports:
      - 5064:5064
      - 5064:5064/udp
      - 5065:5065

networks:

  default:
    external:
      name: pyepics-workshop
