version: "2"

services:

  proxy:
    image: nginx:1.11.6
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always

  ioc:
    build: ioc
    image: pyepics-workshop-ioc
    entrypoint: "true"

  ioc-launcher:
    build: ioc-launcher
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  ioc-relay:
    build: ioc-relay
    ports:
      - 5678:5678
    environment:
      - EPICS_CA_ADDR_LIST=gateway
    restart: always

  ioc-dashboard:
    build: ioc-dashboard
    ports:
      - 9000:9000
    restart: always

  gateway:
    image: dmscid/epics-gateway
    command: -cip 172.111.255.255 -no_cache
    ports:
      - 5064:5064
      - 5064:5064/udp
      - 5065:5065
    restart: always

networks:

  default:
    external:
      name: pyepics-workshop
